name: Run Unit Tests

on: [push]

env:
  JWT_SECRET: ${{ vars.JWT_SECRET }}
  DATABASE_URL: ${{ vars.DATABASE_URL}}
  
jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: mv -f backend/* .
      - run: |
          echo "JWT_SECRET : $JWT_SECRET"
          echo "DATABASE_URL : $DATABASE_URL"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        env:
          JWT_SECRET: ${{ vars.JWT_SECRET}}
          DATABASE_URL: ${{ vars.DATABASE_URL}}

      - run: |
          echo "JWT_SECRET : $JWT_SECRET"
          echo "DATABASE_URL : $DATABASE_URL"
      -   run: npm ci

      - run: npm run test
